project:
  type: website
  output-dir: ../docs

website:
  favicon: https://raw.githubusercontent.com/pat-alt/pat-alt.github.io/main/www/favicon.ico
  title: Julia-themed Quarto
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu:
          - href: examples/article/index.qmd
            text: HTML Article
          - href: examples/revealjs/index.qmd
            text: Revealjs Presentation
          - href: examples/documenter/index.qmd
            text: "Working with `Documenter.jl`" 
          - href: examples/juliacon/index.qmd
            text: JuliaCon Proceedings

format:
  julia-html:
    toc: true



